import { readFileSync } from 'fs';

import { convert } from '../../index';
import { removeFilesByPattern } from '../../utils';
import path from 'path';

const basePath = path.join(__dirname, 'schemas');

describe('Primitive Types', () => {
  beforeAll(async () => {
    await removeFilesByPattern(`${basePath}/*.type.ts`);
    const result = await convert({
      schemaFile: `${basePath}/*.ts`,
      exportFile: (srcPath, fileName) => `${srcPath}/${fileName.replace('Schema', '.type')}`
    });

    expect(result).toBe(true);
  });

  test('String base schema', async () => {
    const readmeContent = readFileSync(`${basePath}/Email.type.ts`).toString();

    expect(readmeContent).toBe(`/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface CompanySchema {
  email?: Email;
}

export type Email = string;

export interface UserSchema {
  email: Email;
}
`);
  });

  test('number base schema', async () => {
    const readmeContent = readFileSync(`${basePath}/Counter.type.ts`).toString();

    expect(readmeContent).toBe(`/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface CompanySchema {
  counter?: Counter;
}

export type Counter = number;

export interface UserSchema {
  counter: Counter;
}
`);
  });

  test('Date base schema', async () => {
    const readmeContent = readFileSync(`${basePath}/DateField.type.ts`).toString();

    expect(readmeContent).toBe(`/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface CompanySchema {
  counter?: DateField;
}

export type DateField = Date;

export interface UserSchema {
  counter: DateField;
}
`);
  });

  test('boolean base schema', async () => {
    const readmeContent = readFileSync(`${basePath}/Boolean.type.ts`).toString();

    expect(readmeContent).toBe(`/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export type Boolean = boolean;

export interface CompanySchema {
  counter?: Boolean;
}

export interface UserSchema {
  counter: Boolean;
}
`);
  });

  test('allow on base schema', async () => {
    const readmeContent = readFileSync(`${basePath}/Allow.type.ts`).toString();

    expect(readmeContent).toBe(`/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export type Blank = string;

export type BlankNull = string | null | '';

/**
 * This is date
 */
export type DateOptions = Date | null;

/**
 * Test Schema Name
 */
export type Name = string;

export type NormalList = 'red' | 'green' | 'blue';

export type NormalRequiredList = 'red' | 'green' | 'blue';

/**
 * nullable
 */
export type NullName = string | null;

export type NullNumber = number | null;

export type Numbers = 1 | 2 | 3 | 4 | 5;
`);
  });

  test('ensure primitive types are exported/imported correctly', async () => {
    const readmeContent = readFileSync(`${basePath}/Using.type.ts`).toString();

    expect(readmeContent).toBe(`/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface UsingOtherTypesSchema {
  property?: string | null | '';
}
`);
  });

  test('union/alternative primitive types', async () => {
    const readmeContent = readFileSync(`${basePath}/Union.type.ts`).toString();

    expect(readmeContent).toBe(`/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface CompanySchema {
  counter?: Union;
}

export type Union = string | number;

export interface UserSchema {
  counter: Union;
}
`);
  });
});
